runtime: python27
threadsafe: true
service: default

automatic_scaling:
  max_concurrent_requests: 1
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 10s
  max_pending_latency: 15s

handlers:
  - url: /default
    script: blank.app
