#!/bin/bash

/home/ec2-user/gcloudsdk/google-cloud-sdk/bin/gcloud app services delete hinson -q

#Timestamp function
timestamp() {
  date
}

TIMESTAMP=$(timestamp)
echo "${TIMESTAMP} :: Shutting down  hinson directory app" >> ~/logs/hinsondir.log